export const lang = {
  es: {
    regresar: 'regresar',
    usuario: 'Usuario',
    bienvenido: 'Bienvenido',
    miUbicacion: 'Ubicacion',
    aficionDiaria: 'Aficion',
    ubicacion: 'Ubicacion',
    cerrarSesion: 'Cerrar Sesion',
    informacionUsuario: 'Informacion de usuario',
    apodo: 'Apodo',
    informacionPerfil: 'Informacion de perfil',
    nombre: 'Nombre',
    apellidoPaterno: 'Apellido paterno',
    apellidoMaterno: 'Apellido materno',
    edad: 'Edad',
    telefono: 'Telefono',
    informacionAficionDiaria: 'Informacion de aficiones diarias',
    creacionAficionDiaria: 'Fecha de creacion',
    contrasenia: 'Contraseña',
    confirmarContrasenia: 'Confirmar contraseña',
    noCoincideContrasenia: 'La contraseñas no conincide',
    registrarse: 'Registrarse',
    cancelar: 'Cancelar',
    iniciarSesion: 'Iniciar sesion',
    crearCuenta: 'Crear cuenta',
    presupuesto: 'Presupuesto',
    dineroMxn: 'Dinero',
    confirmar: 'Confirmar',
    horarioActividad: 'Horario de actividades',
    dia: 'Dia',
    tarde: 'Tarde',
    noche: 'Noche',
    sitio: 'Sitio',
    cerrado: 'Cerrado',
    abierto: 'Abierto',
    movilidad: 'Movilidad',
    carro: 'Vehiculo',
    pie: 'A pie',
    correo: 'Correo',
    recuperarCuenta: 'Recuperar cuenta'
  },
  en: {
    regresar: 'regresar',
    usuario: 'Usuario',
    bienvenido: 'Bienvenido',
    miUbicacion: 'Ubicacion',
    aficionDiaria: 'Aficion',
    ubicacion: 'Ubicacion',
    cerrarSesion: 'Cerrar Sesion',
    informacionUsuario: 'Informacion de usuario',
    apodo: 'Apodo',
    informacionPerfil: 'Informacion de perfil',
    nombre: 'Nombre',
    apellidoPaterno: 'Apellido paterno',
    apellidoMaterno: 'Apellido materno',
    edad: 'Edad',
    telefono: 'Telefono',
    informacionAficionDiaria: 'Informacion de aficiones diarias',
    creacionAficionDiaria: 'Fecha de creacion',
    contrasenia: 'Contraseña',
    confirmarContrasenia: 'Confirmar contraseña',
    noCoincideContrasenia: 'La contraseñas no conincide',
    registrarse: 'Registrarse',
    cancelar: 'Cancelar',
    iniciarSesion: 'Iniciar sesion',
    crearCuenta: 'Crear cuenta',
    presupuesto: 'Presupuesto',
    dineroMxn: 'Dinero',
    confirmar: 'Confirmar',
    horarioActividad: 'Horario de actividades',
    dia: 'Dia',
    tarde: 'Tarde',
    noche: 'Noche',
    sitio: 'Sitio',
    cerrado: 'Cerrado',
    abierto: 'Abierto',
    movilidad: 'Movilidad',
    carro: 'Vehiculo',
    pie: 'A pie',
    correo: 'Correo',
    recuperarCuenta: 'Recuperar cuenta'
  }
}